import React from 'react';
import { Amplify } from 'aws-amplify';
import awsconfig from './aws-exports';
import { withAuthenticator } from '@aws-amplify/ui-react';  // Wraps the app with Auth UI
import { signOut } from '@aws-amplify/auth';  // Import only signOut from @aws-amplify/auth

// Configure Amplify with the aws-exports.js file generated by Amplify
Amplify.configure(awsconfig);

const App = () => {
  // Function to handle sign out
  const handleSignOut = async () => {
    try {
      await signOut(); // Sign out the user
      console.log('Successfully signed out!');
    } catch (error) {
      console.error('Error signing out: ', error);
    }
  };

  return (
    <div>
      <h1>Welcome to the E-commerce App</h1>
      <button onClick={handleSignOut}>Log Out</button>
      {/* Other components like product listing */}
    </div>
  );
};

// Wrap the App component with withAuthenticator to provide Auth UI for sign in/up
export default withAuthenticator(App);
